version: "3"
services:
  mysql-db:
    image: mysql:8
    container_name: recruit_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bach1912
      MYSQL_DATABASE: recruit
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - recruit

  laravel-backend:
    build:
      dockerfile: Dockerfile
      context: "./be"
    command:
      sh -c 'composer install --ignore-platform-reqs && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=8000'
    ports:
      - "8000:8000" # Update the port mapping
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - recruit

  react-frontend:
    build:
      dockerfile: Dockerfile
      context: "./fe"
    command:
      sh -c 'REACT_APP_URL_BE=https://recruit_server.bachnguyencoder.id.vn npm start'
    ports:
      - "3000:3000"
    depends_on:
      - laravel-backend
    networks:
      - recruit

volumes:
  mysql_data:

networks:
  recruit:
