name: Deploy Docker to VPS

on:
  push:
    branches: [main]

jobs:
  test-backend:
    uses: TrinhChung/C-CNNB/.github/workflows/laravel_lint_and_test.yml@main
    secrets: inherit

  deploy-to-vps:
    needs: [test-backend]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull latest code on VPS
        run: |
          sshpass -p "matKhau_1234f" ssh -v -o StrictHostKeyChecking=no "root@159.223.56.70" "cd /root/C-CNNB && git pull origin main"

      - name: Stop and remove old Docker containers, volumes, and images
        run: |
          sshpass -p "matKhau_1234f" ssh -v -o StrictHostKeyChecking=no "root@159.223.56.70" "cd /root/C-CNNB && docker compose down --volumes --rmi all"

      - name: Start Docker Compose on VPS
        run: |
          sshpass -p "matKhau_1234f" ssh -v -o StrictHostKeyChecking=no "root@159.223.56.70" "cd /root/C-CNNB && docker compose up -d"

  build-frontend:
    needs: [deploy-to-vps]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12"  # Choose the version you need

      - name: Install dependencies and build frontend
        run: |
          cd fe
          npm install
          CI=false REACT_APP_URL_BE=https://recruit_server.bachnguyencoder.id.vn npm run build

      - name: Remove old build
        run: |
          sshpass -p "matKhau_1234f" ssh -v -o StrictHostKeyChecking=no "root@159.223.56.70" "rm -r -f /var/www/recruit_app/html/*"
      - name: Move build to VPS
        run: |
          sshpass -p "matKhau_1234f" scp -v -o StrictHostKeyChecking=no -r fe/build/* root@159.223.56.70:/var/www/recruit_app/html
